version: '{build}'

configuration:
  - Debug
  - Release

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 16 2019
      CMAKE_ARGS: -A x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=..\install -DPOG_TESTS=ON -DPOG_EXAMPLES=ON -DPOG_DOWNLOAD_RE2=ON -DPOG_DOWNLOAD_FMT=ON %CMAKE_ARGS% ..

build_script:
  - cmd: cmake --build . --config "%CONFIGURATION%" --target install -- -m

after_build:
  - cmd: tree ..\install /F

test_script:
  - cmd: tests\%CONFIGURATION%\pog_tests.exe

branches:
  only:
    - master
    - /^v?\d+\.\d+.*$/

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
