language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      install: sudo apt-get install -y lcov libfmt-dev libre2-dev tree
      after_success:
        - cd build && rm -rf *
        - cmake -DCMAKE_BUILD_TYPE=Debug -DPOG_TESTS=ON -DPOG_COVERAGE=ON ..
        - cmake --build . -- -j
        - cd .. && ./coverage.sh
        - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
    - os: osx
      osx_image: xcode11
      install: brew install fmt re2 tree

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DPOG_TESTS=ON -DPOG_EXAMPLES=ON -DCMAKE_INSTALL_PREFIX=../install ..
  - cmake --build . --target install -- -j
  - ./tests/pog_tests
  - tree ../install

branches:
  only:
    - master
    - /^v?\d+\.\d+.*$/

notifications:
  email:
    on_success: never
