name: Release
on:
  workflow_run:
    workflows:
      - Test
    tags:
      - v*
    types:
      - completed
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Downloads wheels
        uses: actions/download-artifact@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install twine
        run: |
          python -m pip install twine
      - name: Upload to PyPI
        run: |
          twine upload --skip-existing -u yaramod -p ${{ secrets.pypi_token }} ./*.{whl,tar.gz}
